### ISSUE TITLE
Error: Cannot find module './build/browser/chrome'

### ISSUE THREAD

**Issue by neilD2** [webdriverio/wdio-remote-debugging-service#2]
Hi @christian-bromann ,

I tried to run this repo, but got the following error:

module.js:472
    throw err;
    ^

Error: Cannot find module './build/browser/chrome'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/neil/Downloads/remotedriver/example.js:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by christian-bromann** [comment]
Please make sure you build the project calling `grunt build`
